### PR TITLE
20200516 - se-linux support and example crontab

### PR DESCRIPTION
**Pull request by indianfoodyummy**
This is the code I sent you as a diff like maybe 9-12 months ago, and I just got around to submitting through proper git process.  Sorry for the delay.  The se-linux code is added to ensure that if running on an enforcing se-linux system, it will set proper file attributes on the over-written .rpz file at the end of your script.

Additionally, I included an example crontab file, in case people want to have your script run every day, and want to collect the output in local host email.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Wouldn't commit https://github.com/Trellmor/bind-adblock/pull/20/commits/89d2a254cc0f2557f90a97208905e66cec07e607 cause the script to fail on systems where /usr/sbin/getenforce is not available?

**Comment by indianfoodyummy** [comment]
> Wouldn't commit [89d2a25](https://github.com/Trellmor/bind-adblock/commit/89d2a254cc0f2557f90a97208905e66cec07e607) cause the script to fail on systems where /usr/sbin/getenforce is not available?

Is that possible?  I thought that all Linux would now have baseline selinux binaries at least to confirm if selinux is disabled?  However, I can easily add a test, if preferable?

**Comment by indianfoodyummy** [comment]
Please forgive my general ignorance of git process... I proposed a change in May to set selinux-required mandatory access attributes on the rpz file, so that this can work on selinux-enabled systems...
Today (september), I proposed a change to add a "--empty" command-line argument that just sets the domain list to empty-set, so that you end up with an  rpz file that just has the header, but no entries... I found that bind won't "delete" a zone that is an rpz vi rndc command... so this is a way around that, in case you want to temporarily disable rpz blocking (in practice), via a single command (no vi, then systemctl required).

**Comment by anders-larsson** [comment]
Not the maintainer of the project but IMHO yes.

**Comment by indianfoodyummy** [comment]
As identified by anders-larsson, I added some logic to verify the 2 x selinux commands actually exist and are executable before calling them.

**Comment by Trellmor** [comment]
Sorry for taking so long to merge this. PR look good with the addition of checking if the selinux commands exist.

**Pull request merged**
